# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'DYZB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DYZB

pod 'Alamofire', '~> 4.5.0'
pod 'Kingfisher'


  target 'DYZBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DYZBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
